dependencies:
- name: zookeeper
  version: 0.4.3
  repository: https://raw.githubusercontent.com/bitbouncer/helm-charts-storage/master/
- name: kafka
  version: 0.2.11
  repository: https://raw.githubusercontent.com/bitbouncer/helm-charts-storage/master/
- name: schema-registry
  version: 0.1.0
  repository: https://raw.githubusercontent.com/bitbouncer/helm-charts-storage/master/

